version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pedales
      POSTGRES_PASSWORD: pedales
      POSTGRES_DB: pedales
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedales"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://pedales:pedales@db:5432/pedales?schema=public
      JWT_SECRET: dev-secret-change-me
      ADMIN_EMAIL: admin@tienda.com
      ADMIN_PASSWORD: admin123
      PORT: 3001
      MP_MOCK: "false"
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN:-APP_USR-2665813189459429-082714-6ddcce5fc59d6226cba3f31e1bec9d0d-3633650198}
      MP_SUCCESS_URL: http://localhost:3003/checkout/success
      MP_FAILURE_URL: http://localhost:3003/checkout/failure
      MP_PENDING_URL: http://localhost:3003/checkout/pending
      MP_WEBHOOK_SECRET: ${MP_WEBHOOK_SECRET:-REPLACE_WITH_YOUR_MERCADO_PAGO_WEBHOOK_SECRET}
      MP_NOTIFICATION_URL: ${MP_NOTIFICATION_URL:-https://YOUR_PUBLIC_DOMAIN/api/payments/webhook}
      MP_CURRENCY_ID: ARS
      FRONTEND_URL: http://localhost:3003
      ANDREANI_MOCK: "true"
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL:-onboarding@resend.dev}
      ADMIN_NOTIFICATION_EMAIL: ${ADMIN_NOTIFICATION_EMAIL:-}
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    build: ./web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      API_INTERNAL_URL: http://api:3001
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3003:3000"   # (o el puerto que hayas dejado vos) 
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next

  admin:
    build: ./admin
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3002:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next

volumes:
  db_data:
