services:
  - type: web
    name: nanook-api
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./api/Dockerfile.prod
    dockerContext: ./api
    healthCheckPath: /api
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: PORT
        value: 3001
      - key: API_PUBLIC_URL
        value: https://api.tiendananook.store
      - key: MP_MOCK
        value: true # pasar a "false" cuando estén activas las credenciales de producción de MP
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MP_SUCCESS_URL
        value: https://tiendananook.store/checkout/success
      - key: MP_FAILURE_URL
        value: https://tiendananook.store/checkout/failure
      - key: MP_PENDING_URL
        value: https://tiendananook.store/checkout/pending
      - key: MP_WEBHOOK_SECRET
        sync: false
      - key: MP_NOTIFICATION_URL
        value: https://api.tiendananook.store/api/payments/webhook
      - key: MP_CURRENCY_ID
        value: ARS
      - key: FRONTEND_URL
        value: https://tiendananook.store
      - key: ADMIN_URL
        value: https://admin.tiendananook.store
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: ADMIN_NOTIFICATION_EMAIL
        sync: false

  - type: web
    name: nanook-web
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./web/Dockerfile.prod
    dockerContext: ./web
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.tiendananook.store
      - key: API_INTERNAL_URL
        value: https://api.tiendananook.store

  - type: web
    name: nanook-admin
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./admin/Dockerfile.prod
    dockerContext: ./admin
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.tiendananook.store
